# Generated by Django 2.2 on 2019-06-22 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('ranks', models.IntegerField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Team')),
            ],
            options={
                'verbose_name_plural': 'PlayerInfo',
            },
        ),
    ]
